theme: jekyll-theme-minimal
title: Sarthak Arora
description: <a href ="https://www.instagram.com/acrossthedelta/">ğŸ“·</a> <a href ="https://soundcloud.com/auralrush">ğŸµ</a> 
 
logo: disp.jpg
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-youtube
